package com.taomei.dao.mapper;

import com.taomei.dao.entities.Users;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserMapper {
    /**
     *根据账号来查询账号，用于判断该账号是否被注册
     * @param account 用户待注册的账号
     * @return 查询出来的account
     */
    String selectAccountByAccount(String account);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    int insertSelective(Users record);
}